install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages("openxlsx", dependencies = TRUE)
install.packages("ggpubr")
install.packages("factoextra")
install.packages("pheatmap")
install.packages('BiocManager')
BiocManager::install('EnhancedVolcano')
BiocManager::install('ReactomePA')
BiocManager::install("clusterProfiler")
BiocManager::install("org.Hs.eg.db")
BiocManager::install("preprocessCore")